### PR TITLE
Task 5: Integration with S3

### PR DESCRIPTION
**Pull request by HannaHerman**
Link to CloudFront URL
[click to follow](https://d2su5kr4943734.cloudfront.net/)

Link to FE PR
[click to follow](https://github.com/HannaHerman/shop-angular-cloudfront/pull/4/files)

Import Service API url
https://a3rz7omkui.execute-api.eu-west-1.amazonaws.com/dev/import?name=products.csv

1 - File serverless.yml contains configuration for importProductsFile function
3 - The importProductsFile lambda function returns a correct response which can be used to upload a file into the S3 bucket
4 - Frontend application is integrated with importProductsFile lambda
5 - The importFileParser lambda function is implemented and serverless.yml contains configuration for the lambda

+1  - async/await is used in lambda functions
+1 - At the end of the stream the lambda function should move the file from the uploaded folder into the parsed folder (move the file means that file should be copied into a new folder in the same bucket called parsed, and then deleted from uploaded folder)

Product schema:
{
  id: 'ad9e524d-1f4b-4ccb-b470-1bb211808c43',
  title: 'Horse',
  count: '17',
  description: 'Fast Horse',
  price: '189'
}

### CODE REVIEW

**Comment by ibratnawaz** [comment]
ALGTM

**Comment by qqil** [comment]
Looks good. 

I want to recommend you move initialization of S3 client outside of lambda function, it described [here](https://docs.aws.amazon.com/lambda/latest/dg/best-practices.html):


> Take advantage of execution environment reuse to improve the performance of your function.
> Initialize SDK clients and database connections outside of the function handler, and cache static assets locally in the /tmp directory. 
> Subsequent invocations processed by the same instance of your function can reuse these resources. This saves cost by reducing function run time.
> 

My mark is 7 points.

```
5 - The importFileParser lambda function is implemented and serverless.yml contains configuration for the lambda

+1 (for JS only) - async/await is used in lambda functions
+1 (All languages) - At the end of the stream the lambda function should move the file from the uploaded folder into the parsed folder (move the file means that file should be copied into a new folder in the same bucket called parsed, and then deleted from uploaded folder)
```

**Comment by HannaHerman** [comment]
@qqil Thanks a lot for comments and for the link

**Comment by niyowski** [comment]
LGTM. My mark is 7.

**Review by niyowski — APPROVED** [review]

**Pull request merged**
